/* ============================================================================
   PROJECT NEO · THE OBJECT'S TECHNICAL DEPTH.
   ----------------------------------------------------------------------------
   SERVER component. Renders one `TableEnrichment` record — 94 of the 105
   blueprint tables carry one.

   WHY THIS IS A SEPARATE LAYER AND NOT PART OF THE BLUEPRINT

     data/sapData.* is GENERATED by scripts/extract-xlsx.mjs from the two
     migration workbooks and is regenerated, never edited. The workbooks do not
     hold an ABAP snippet, an index hint or a debug entry point, so this content
     cannot live there — it lives beside it, keyed by table name, and merges at
     render. That is also why it was invisible: nothing in NEO imported it.

   THE RULE THIS COMPONENT FOLLOWS

     Every field is printed exactly as written, and the SOURCES are printed with
     it. A performance claim or an index hint is only worth what its provenance
     is worth, and the enrichment records that provenance per table (SE11, SAP
     Help). Hiding it would turn a cited fact into an assertion.

     Code is rendered in a real <pre>: LTR, monospace, horizontally scrollable,
     never wrapped. A wrapped ABAP snippet is a wrong ABAP snippet.
   ========================================================================== */

import { BadgeCheck, Braces, Bug, Database, Gauge, KeyRound, Link2, ScrollText, Zap } from "lucide-react";
import type { TableEnrichment } from "@/data/table-enrichment";

/** A titled block that renders only when the enrichment carries the field. */
function Block({
  icon, title, children,
}: {
  icon: React.ReactNode; title: string; children: React.ReactNode;
}) {
  return (
    <div className="nod-b">
      <h3 className="nod-h">
        <span className="nod-h-i" aria-hidden="true">{icon}</span>
        {title}
      </h3>
      {children}
    </div>
  );
}

const List = ({ items, tone }: { items: string[]; tone?: string }) => (
  <ul className="nod-l" data-tone={tone}>
    {items.map((x, i) => <li key={i}>{x}</li>)}
  </ul>
);

/** One worked example. `pre` + LTR + no wrapping: an ABAP or SQL statement that
 *  wraps at a container edge is no longer the statement that was written. */
const Code = ({ code }: { code: string }) => (
  <pre className="nod-code" dir="ltr" tabIndex={0}><code>{code}</code></pre>
);

export function ObjectDepth({ e }: { e: TableEnrichment }) {
  return (
    <div className="nod">
      {e.purposeDeep ? (
        <p className="nod-purpose">{e.purposeDeep}</p>
      ) : null}

      {e.primaryKey?.length ? (
        <Block icon={<KeyRound size={13} strokeWidth={2} />} title="שדות המפתח ומה הם אומרים">
          <List items={e.primaryKey} tone="pk" />
        </Block>
      ) : null}

      {e.foreignKeys?.length ? (
        <Block icon={<Link2 size={13} strokeWidth={2} />} title="מפתחות זרים — לאן הטבלה מצביעה">
          <List items={e.foreignKeys} tone="fk" />
        </Block>
      ) : null}

      {e.indexes?.length ? (
        <Block icon={<Database size={13} strokeWidth={2} />} title="נתיב הגישה">
          <List items={e.indexes} />
        </Block>
      ) : null}

      {e.perfNotes?.length ? (
        <Block icon={<Gauge size={13} strokeWidth={2} />} title="שיקולי ביצועים">
          <List items={e.perfNotes} />
        </Block>
      ) : null}

      {/* THE S/4 DATA-MODEL LINE. Only 9 of the 94 tables carry one, because
          only 9 of them are actually touched by MATDOC / ACDOCA. It is given
          its own emphasis rather than buried in the performance list — on this
          platform it is the sentence a migration reader came for. */}
      {e.matdocNote ? (
        <div className="nod-matdoc">
          <h3 className="nod-h">
            <span className="nod-h-i" aria-hidden="true"><Zap size={13} strokeWidth={2} /></span>
            מודל הנתונים ב-S/4HANA
          </h3>
          <p>{e.matdocNote}</p>
        </div>
      ) : null}

      {e.abapExample ? (
        <Block icon={<Braces size={13} strokeWidth={2} />} title="ABAP">
          <Code code={e.abapExample} />
        </Block>
      ) : null}

      {e.sqlExample ? (
        <Block icon={<Database size={13} strokeWidth={2} />} title="SQL · CDS">
          <Code code={e.sqlExample} />
        </Block>
      ) : null}

      {e.debugExample ? (
        <Block icon={<Bug size={13} strokeWidth={2} />} title="איך בודקים את זה במערכת">
          <p className="nod-p">{e.debugExample}</p>
        </Block>
      ) : null}

      {/* PROVENANCE. Printed, not implied. */}
      {e.sources?.length || e.verified ? (
        <footer className="nod-src">
          {e.verified ? (
            <span className="nod-vf" data-v={e.verified}>
              <BadgeCheck size={12} strokeWidth={2.25} aria-hidden="true" />
              {e.verified === "verified" ? "מאומת מול DDIC ותיעוד SAP" : "דורש אימות מול SAP"}
            </span>
          ) : null}
          {e.sources?.length ? (
            <span className="nod-src-l">
              <ScrollText size={12} strokeWidth={2} aria-hidden="true" />
              {e.sources.join(" · ")}
            </span>
          ) : null}
        </footer>
      ) : null}
    </div>
  );
}
