// ===== AUTO-GENERATED by scripts/extract-xlsx.mjs — DO NOT EDIT BY HAND =====
// Source of truth: docs/SAP_PM_ECC6_to_S4_Migration.xlsx,
//                  docs/SAP_PPPI_ECC6_to_S4_Migration.xlsx
// Real CBC PM + PP-PI migration blueprints ported verbatim (zero truncation):
// fields, keys, BAPIs/IDocs (incl Zetes/Daymax), S/4 notes, Fiori apps,
// and the full ER parent-child relation map.
import type { SAPModuleData, SAPTable } from "@/lib/types";
import { PM_DATA } from "@/data/sapData.pm";
import { PPPI_DATA } from "@/data/sapData.pppi";

export { PM_DATA, PPPI_DATA };

export const MODULES: SAPModuleData[] = [PM_DATA, PPPI_DATA];

/** Flattened table list across both modules — feeds the Omni-Search index. */
export const ALL_TABLES: SAPTable[] = MODULES.flatMap((m) =>
  m.topics.flatMap((t) => t.tables),
);
