// ===== Project NEO Cockpit — deterministic data extraction =====
// Reads the two standalone HTML knowledge bases, evals their embedded
// `const DATA = {...}` object literals, and emits a strongly-typed
// `data/sapData.ts`. No row is hand-typed -> zero truncation, zero invention.
//
// Run: node scripts/extract-data.mjs

import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SRC_DIR = path.join(ROOT, "source");
const DOWNLOADS = path.join(os.homedir(), "Downloads");

const SOURCES = [
  { module: "PP-PI", title: "SAP PP-PI Hub", file: "index_pppi_standalone.html", expect: 68 },
  { module: "PM", title: "SAP PM Hub", file: "index_pm_standalone.html", expect: 58 },
];

fs.mkdirSync(SRC_DIR, { recursive: true });

// --- Pull `const DATA = { ... }` out of an HTML file via brace balancing ---
function extractDATA(html) {
  const marker = "const DATA";
  const i = html.indexOf(marker);
  if (i < 0) throw new Error("`const DATA` not found");
  let k = html.indexOf("{", i);
  const start = k;
  let depth = 0;
  for (; k < html.length; k++) {
    const c = html[k];
    if (c === "{") depth++;
    else if (c === "}") {
      depth--;
      if (depth === 0) {
        k++;
        break;
      }
    }
  }
  const literal = html.slice(start, k);
  // Trusted local input. eval keeps the source object shape verbatim.
  return new Function(`return (${literal});`)();
}

const A = (v) => (Array.isArray(v) ? v : []);
const S = (v) => (v == null ? "" : String(v));

function normalizeModule({ module, title, file, expect }) {
  // Copy source into the repo for provenance, then read it.
  const downloadPath = path.join(DOWNLOADS, file);
  const repoPath = path.join(SRC_DIR, file);
  if (fs.existsSync(downloadPath)) fs.copyFileSync(downloadPath, repoPath);
  if (!fs.existsSync(repoPath))
    throw new Error(`source HTML missing: ${file} (looked in Downloads and source/)`);

  const DATA = extractDATA(fs.readFileSync(repoPath, "utf8"));

  const seenIds = new Map();
  const mkId = (name, topicIdx) => {
    const base = `${module}:${name}`;
    const n = seenIds.get(base) ?? 0;
    seenIds.set(base, n + 1);
    return n === 0 ? base : `${base}#${topicIdx}`;
  };

  const topics = A(DATA.topics).map((t) => {
    const topicIdx = Number(t.idx);
    const topicTitle = S(t.title);
    const tables = A(t.tables).map((tb) => ({
      id: mkId(S(tb.name), topicIdx),
      module,
      topicIdx,
      topicTitle,
      tableName: S(tb.name),
      descriptionHe: S(tb.he),
      descriptionEn: S(tb.en),
      tcodes: S(tb.tcodes),
      sqlJoinSnippet: S(tb.join),
      guideHe: S(tb.guide),
      s4Note: S(tb.s4),
      helpUrl: tb.help_url ? S(tb.help_url) : undefined,
      helpLbl: tb.help_lbl ? S(tb.help_lbl) : undefined,
      funcs: A(tb.funcs).map((f) => [S(f[0]), S(f[1])]),
      progs: A(tb.progs).map((p) => [S(p[0]), S(p[1])]),
      fields: A(tb.fields).map((fl) => ({
        tech: S(fl.tech),
        en: S(fl.en),
        he: S(fl.he),
        dt: S(fl.dt),
        len: S(fl.len),
        key: S(fl.key),
      })),
      migrationStatus: "Not started",
    }));
    return {
      idx: topicIdx,
      module,
      title: topicTitle,
      theme: t.theme ? S(t.theme) : undefined,
      tables,
      ops: {
        tcodes: A(t.ops?.tcodes).map((r) => A(r).map(S)),
        interfaces: A(t.ops?.interfaces).map((r) => A(r).map(S)),
      },
    };
  });

  const tableCount = topics.reduce((n, t) => n + t.tables.length, 0);
  if (tableCount !== expect) {
    throw new Error(
      `[${module}] table count ${tableCount} !== expected ${expect} — refusing to write (possible truncation)`,
    );
  }

  return {
    module,
    title,
    topics,
    joins: A(DATA.joins).map((j) => ({ table: S(j.table), join: S(j.join), he: S(j.he) })),
    tcodesDir: A(DATA.tcodes_dir).map((r) => A(r).map(S)),
    tools: DATA.tools_dir ? A(DATA.tools_dir).map((r) => A(r).map(S)) : undefined,
    ppvs: DATA.ppvs ? A(DATA.ppvs).map((r) => A(r).map(S)) : undefined,
    simplification: DATA.simplification ?? undefined,
    config: DATA.config ?? undefined,
    statuses: A(DATA.statuses).map(S),
  };
}

const PPPI = normalizeModule(SOURCES[0]);
const PM = normalizeModule(SOURCES[1]);

const banner = `// ===== AUTO-GENERATED by scripts/extract-data.mjs — DO NOT EDIT BY HAND =====
// Source: source/index_pppi_standalone.html, source/index_pm_standalone.html
// Real CBC PP-PI + PM knowledge bases ported verbatim (zero truncation).
import type { SAPModuleData, SAPTable } from "@/lib/types";
`;

const out = `${banner}
export const PPPI_DATA = ${JSON.stringify(PPPI, null, 2)} as SAPModuleData;

export const PM_DATA = ${JSON.stringify(PM, null, 2)} as SAPModuleData;

export const MODULES: SAPModuleData[] = [PM_DATA, PPPI_DATA];

/** Flattened table list across both modules — feeds the Omni-Search index. */
export const ALL_TABLES: SAPTable[] = MODULES.flatMap((m) =>
  m.topics.flatMap((t) => t.tables),
);
`;

fs.mkdirSync(path.join(ROOT, "data"), { recursive: true });
fs.writeFileSync(path.join(ROOT, "data", "sapData.ts"), out, "utf8");

console.log("✓ data/sapData.ts written");
console.log(`  PP-PI: ${PPPI.topics.length} topics, ${PPPI.topics.reduce((n, t) => n + t.tables.length, 0)} tables, ${PPPI.joins.length} joins`);
console.log(`  PM   : ${PM.topics.length} topics, ${PM.topics.reduce((n, t) => n + t.tables.length, 0)} tables, ${PM.joins.length} joins`);
console.log(`  ALL_TABLES: ${PPPI.topics.reduce((n, t) => n + t.tables.length, 0) + PM.topics.reduce((n, t) => n + t.tables.length, 0)}`);
