// Generates lib/route-manifest.generated.ts — a string-only mirror of every
// dynamic route's generateStaticParams. Lets the client <SmartLink> resolver
// ship a few KB of code strings instead of pulling the full SAP datasets
// (sapData PM+PP-PI, the 1.3 MB tx-intel, impact graph, transactions) into the
// browser bundle of every page that renders a link.
//
// Run: npx tsx scripts/gen-route-manifest.mts   (wired as `prebuild`)
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { registryCodes } from "@/lib/tx-registry";
import { listTcodes, listFuncs } from "@/lib/object-intel";
import { listCdsViews } from "@/data/cds-map";
import { ALL_TABLES } from "@/lib/data";
import { HR_BW_NAMES } from "@/lib/hr-bw-adapter";
import { verifiedNames } from "@/data/verified-objects";
import { appCodes } from "@/lib/apps-intel";
import { allImpactNames } from "@/lib/impact";
import { TRANSACTIONS } from "@/data/transactions";

const uniq = (a: string[]) => [...new Set(a.filter(Boolean))].sort();

const manifest = {
  objects: uniq([...ALL_TABLES.map((t) => t.tableName), ...HR_BW_NAMES, ...verifiedNames()]),
  tcodes: uniq([...registryCodes(), ...listTcodes()].map((x) => x.toUpperCase())),
  bapiFm: uniq([...listFuncs("BAPI"), ...listFuncs("FM")]),
  idocs: uniq(listFuncs("IDoc")),
  cds: uniq(listCdsViews()),
  apps: uniq(appCodes()),
  impact: uniq(allImpactNames()),
  transactions: uniq(TRANSACTIONS.map((t) => t.code)),
};

const out =
  "// AUTO-GENERATED by scripts/gen-route-manifest.mts — DO NOT EDIT BY HAND.\n" +
  "// Regenerate with: npx tsx scripts/gen-route-manifest.mts (runs on prebuild).\n" +
  "// String-only mirror of every dynamic route's generateStaticParams, so the\n" +
  "// client SmartLink resolver never bundles the full SAP datasets.\n" +
  `export const ROUTE_MANIFEST = ${JSON.stringify(manifest, null, 0)} as const;\n`;

const target = fileURLToPath(new URL("../lib/route-manifest.generated.ts", import.meta.url));
writeFileSync(target, out);
console.log(
  "route-manifest generated:",
  Object.fromEntries(Object.entries(manifest).map(([k, v]) => [k, v.length])),
);
